#!/bin/bash

# Copyright (C) 2021 The Android Open Source Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# launcher script for cts-root-tradefed harness
# can be used from an Android build environment, or a standalone cts-root zip

UTILS_SCRIPT="$(dirname $(realpath $0))/test-utils-script"

if [ ! -f "${UTILS_SCRIPT}" ]
then
  UTILS_SCRIPT="${ANDROID_BUILD_TOP}/platform_testing/scripts/test-utils-script"
fi

if [ ! -f "${UTILS_SCRIPT}" ]
then
  echo -e "Cannot find test-utils-script in the same location as this script" \
          "and ANDROID_BUILD_TOP is not defined."
  exit 1
fi

source ${UTILS_SCRIPT}

checkPath adb
checkPath java
checkJavaVersion java

RDBG_FLAG=$(getRemoteDbgFlag)

# get OS
HOST=`uname`
if [ "$HOST" == "Linux" ]; then
    OS="linux-x86"
elif [ "$HOST" == "Darwin" ]; then
    OS="darwin-x86"
else
    echo "Unrecognized OS"
    exit
fi

# check if in Android build env
if [ ! -z "${ANDROID_BUILD_TOP}" ]; then
    if [ ! -z "${ANDROID_HOST_OUT}" ]; then
      CTS_ROOT_ROOT=${ANDROID_HOST_OUT}/cts_root
    else
      CTS_ROOT_ROOT=${ANDROID_BUILD_TOP}/${OUT_DIR:-out}/host/${OS}/cts_root
    fi
    if [ ! -d ${CTS_ROOT_ROOT} ]; then
        echo "Could not find $CTS_ROOT_ROOT in Android build environment. Try 'make cts_root'"
        exit
    fi;
fi;

if [ -z ${CTS_ROOT_ROOT} ]; then
    # assume we're in an extracted cts-root install
    CTS_ROOT_ROOT="$(dirname $0)/../.."
fi;

JAR_DIR=${CTS_ROOT_ROOT}/android-cts_root/tools

for JAR in ${JAR_DIR}/*.jar; do
    JAR_PATH=${JAR_PATH}:${JAR}
done

LIB_DIR=${CTS_ROOT_ROOT}/android-cts_root/lib
loadSharedLibraries "$HOST" "$LIB_DIR"

# include any host-side test jars
for j in ${CTS_ROOT_ROOT}/android-cts_root/testcases/*.jar; do
    JAR_PATH=${JAR_PATH}:$j
done

java $RDBG_FLAG -cp ${JAR_PATH} -DCTS_ROOT_ROOT=${CTS_ROOT_ROOT} com.android.compatibility.common.tradefed.command.CompatibilityConsole "$@"
